(in-package #:mistral)

;; define the environment variable "MISTRAL_API_KEY" with the value of your mistral API key


(defvar model-host "https://api.mistral.ai/v1/chat/completions")
;; Available models:
;;
;;   "mistral-tiny" powered by Mistral-7B-v0.2
;;   "mistral-small" powered Mixtral-8X7B-v0.1, a sparse mixture of experts model with 12B active parameters
;;   "mistral-medium" powered by a larger internal prototype model
;;

(defun mistral-helper (curl-command)
  (let ((response
          (uiop:run-program
           curl-command
           :output :string)))
    (with-input-from-string
        (s response)
      (let* ((json-as-list (json:decode-json s)))
        ;; extract text (this might change if mistral changes JSON return format):
        (cdr (assoc :content (cdr (assoc :message (cadr (assoc :choices json-as-list))))))))))

(defun completions (starter-text max-tokens)
  (let* ((d
          (cl-json:encode-json-to-string
           `((:messages . (((:role . "user") (:content . ,starter-text))))
             (:model . "mistral-small")
             (:max_tokens . ,max-tokens))))
         (curl-command
          (concatenate
           'string
           "curl " model-host
           " -H \"Content-Type: application/json\""
           " -H \"Authorization: Bearer " (uiop:getenv "MISTRAL_API_KEY") "\" " 
           " -d '" d "'")))
    (mistral-helper curl-command)))

(defun summarize (some-text max-tokens)
  (let* ((curl-command
          (concatenate
           'string
           "curl " model-host
           " -H \"Content-Type: application/json\""
           " -H \"Authorization: Bearer " (uiop:getenv "MISTRAL_API_KEY") "\" " 
           " -d '{\"messages\": [{\"role\": \"user\", \"content\": \"Sumarize: " some-text 
           "\"}], \"model\": \"mistral-small\", \"max_tokens\": " (write-to-string max-tokens)  "}'")))
    (mistral-helper curl-command)))

(defun answer-question (question-text max-tokens)
  (let ((q-text
          (concatenate
           'string
           "\nQ: " question-text "\nA:")))
    (completions q-text max-tokens)))


(defun embeddings (text)
  (let* ((curl-command
          (concatenate
           'string
           "curl  https://api.mistral.ai/v1/embeddings "
           " -H \"Content-Type: application/json\""
           " -H \"Authorization: Bearer " (uiop:getenv "MISTRAL_API_KEY") "\" " 
           " -d '{\"input\": [\"" text "\"], \"model\": \"mistral-embed\"}'")))
    (let ((response
           (uiop:run-program
            curl-command
            :output :string)))
      ;;(princ curl-command)
      ;;(pprint response)
      (with-input-from-string
          (s response)
        (let ((json-as-list (json:decode-json s)))
          ;; return a list of 1024 floats:
          (cdr (assoc :embedding (cadr (assoc :data json-as-list)))))))))

(defun dot-product-recursive (a b) ;; generated by Bing+ChatGPT Search
  (print "dot-product")
  (if (or (null a) (null b))
      0
      (+ (* (first a) (first b))
         (dot-product (rest a) (rest b)))))

(defun dot-product (list1 list2)
  (let ((sum 0))
    (loop for x in list1
          for y in list2
          do
               (setf sum (+ sum (* x y))))
    sum))

;; (print (dot-product '(1 2 3) '(4 5 6)))
;; (print (mistral::embeddings "John bought a new car"))

#|

(print (mistral:completions "The President went to Congress" 20))

(print (mistral:summarize "Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass one-thousandth that of the Sun, but two-and-a-half times that of all the other planets in the Solar System combined. Jupiter is one of the brightest objects visible to the naked eye in the night sky, and has been known to ancient civilizations since before recorded history. It is named after the Roman god Jupiter.[19] When viewed from Earth, Jupiter can be bright enough for its reflected light to cast visible shadows,[20] and is on average the third-brightest natural object in the night sky after the Moon and Venus." 30))

(print (mistral:answer-question "Where were the 1992 Olympics held?" 60))
(print (mistral:answer-question "Where is the Valley of Kings?" 60))
(Print (mistral:answer-question "Mary is 30 years old and Bob is 25. Who is older?" 60))

|#
