(terpri)
(terpri)
(princ "*************CLML Examples packacke loaded *****")
(terpri)
(princ "Try running:")
(terpri)
(princ "(in-package #:clmltest)")
(terpri)
(princ "(clml-cancer-data-svm-example)")
(terpri)
(princ "(clml-read-data-example)")
(terpri)
(princ "(clml-kmeans-example)")
(terpri)
(princ "(clml-tests-example)")
(terpri)
(terpri)

