(ql:quickload '(:drakma :plump :cl-ppcre))

(defun text-node-p (node)
  (typep node 'plump:text-node))

(defun element-node-p (node)
  (typep node 'plump:element))

(defun ignore-tag-p (tag)
  (member tag '("script" "style" "head" "noscript" "iframe")
          :test #'string-equal))

(defun block-element-p (tag)
  (member tag '("p" "div" "li" "br" "h1" "h2" "h3" "h4" "h5" "h6" "tr" "article" "section" "aside")
          :test #'string-equal))

(defun html-to-markdown (node)
  "Recursively converts a plump HTML node into Markdown."
  (cond
    ((text-node-p node)
     (plump:text node))
    ((element-node-p node)
     (let* ((tag (plump:tag-name node))
            (inner-md (with-output-to-string (s)
                        (loop for child across (plump:children node)
                              do (write-string (html-to-markdown child) s)))))
       (cond
         ((ignore-tag-p tag) "")
         ((string-equal tag "h1")
          (format nil "~%__H1__~%# ~A~%__H1__~%" (string-trim '(#\Space #\Tab #\Newline #\Return) inner-md)))
         ((string-equal tag "h2")
          (format nil "~%__H2__~%## ~A~%__H2__~%" (string-trim '(#\Space #\Tab #\Newline #\Return) inner-md)))
         ((string-equal tag "h3") (format nil "~%### ~A~%~%" (string-trim '(#\Space #\Tab) inner-md)))
         ((string-equal tag "h4") (format nil "~%#### ~A~%~%" (string-trim '(#\Space #\Tab) inner-md)))
         ((string-equal tag "h5") (format nil "~%##### ~A~%~%" (string-trim '(#\Space #\Tab) inner-md)))
         ((string-equal tag "h6") (format nil "~%###### ~A~%~%" (string-trim '(#\Space #\Tab) inner-md)))
         ((string-equal tag "p")  (format nil "~%~A~%~%" (string-trim '(#\Space #\Tab #\Newline #\Return) inner-md)))
         ((string-equal tag "br") (format nil "~%"))
         ((string-equal tag "strong") (format nil "**~A**" inner-md))
         ((string-equal tag "b")      (format nil "**~A**" inner-md))
         ((string-equal tag "em")     (format nil "*~A*" inner-md))
         ((string-equal tag "i")      (format nil "*~A*" inner-md))
         ((string-equal tag "code")   (format nil "`~A`" inner-md))
         ((string-equal tag "pre")    (format nil "~%```~%~A~%```~%" inner-md))
         ((string-equal tag "a")
          (let ((href (plump:attribute node "href")))
            (if (and href (> (length (string-trim '(#\Space #\Tab) inner-md)) 0))
                (format nil "[~A](~A)" (string-trim '(#\Space #\Tab #\Newline #\Return) inner-md) href)
                inner-md)))
         ((string-equal tag "img")
          (let ((src (plump:attribute node "src"))
                (alt (or (plump:attribute node "alt") "image")))
            (if src
                (format nil "![~A](~A)" alt src)
                "")))
         ((string-equal tag "li")
          (format nil "* ~A~%" (string-trim '(#\Space #\Tab #\Newline #\Return) inner-md)))
         ((block-element-p tag)
          (format nil "~%~A~%" inner-md))
         (t inner-md))))
    ((typep node 'plump:nesting-node)
     (with-output-to-string (s)
       (loop for child across (plump:children node)
             do (write-string (html-to-markdown child) s))))
    (t "")))

(defun clean-markdown-whitespace (text)
  "Cleans up excessive spaces and newlines in the Markdown, preserving spacing for H1/H2."
  (let* ((n (format nil "~%"))
         ;; 1. Clean up lines that contain only whitespace
         (text (cl-ppcre:regex-replace-all "(?m)^[ \\t]+$" text ""))
         ;; 2. Collapse double spaces
         (text (cl-ppcre:regex-replace-all "[ \\t]+" text " "))
         ;; 3. Collapse multiple consecutive newlines to at most 2 newlines (1 blank line)
         (text (cl-ppcre:regex-replace-all (format nil "~A{3,}" n) text (format nil "~A~A" n n)))
         ;; 4. Replace __H1__ markers with 4 newlines (3 blank lines)
         (text (cl-ppcre:regex-replace-all (format nil "~A*__H1__~A*" n n) text (format nil "~A~A~A~A" n n n n)))
         ;; 5. Replace __H2__ markers with 3 newlines (2 blank lines)
         (text (cl-ppcre:regex-replace-all (format nil "~A*__H2__~A*" n n) text (format nil "~A~A~A" n n n)))
         ;; 6. Trim leading/trailing whitespace of the whole text
         (text (string-trim '(#\Space #\Tab #\Newline #\Return) text)))
    text))

(defun fetch-and-print-markdown (url)
  "Fetches the URL and prints content converted to Markdown."
  (format t "Fetching ~A...~%" url)
  (let* ((html-content (drakma:http-request url))
         (parsed-html (plump:parse html-content))
         (raw-markdown (html-to-markdown parsed-html))
         (cleaned-markdown (clean-markdown-whitespace raw-markdown)))
    (format t "~A~%" cleaned-markdown)))

(fetch-and-print-markdown "https://markwatson.com")
