;;;; microgpt.lisp — Karpathy's microGPT in dependency-free Common Lisp

(defpackage #:microgpt (:use #:cl) (:export #:run-microgpt))
(in-package #:microgpt)

(defun random-gauss (mean std)
  (+ mean (* std (sqrt (* -2 (log (max (random 1.0) 1e-15)))) (cos (* 2 pi (random 1.0))))))

(defun shuffle-list (seq)
  (let ((v (coerce seq 'vector)))
    (loop for i from (1- (length v)) downto 1 for j = (random (1+ i))
          do (rotatef (aref v i) (aref v j)))
    (coerce v 'list)))

(defun read-lines (file)
  (with-open-file (s file :if-does-not-exist nil)
    (when s
      (loop for line = (read-line s nil) while line
            for tr = (string-trim '(#\Space #\Tab #\Newline #\Return) line)
            when (plusp (length tr)) collect tr))))

(defparameter *docs* nil) (defparameter *uchars* nil) (defparameter *bos* nil)
(defparameter *vocab-size* nil) (defparameter *n-layer* 1) (defparameter *n-embd* 16)
(defparameter *block-size* 16) (defparameter *n-head* 4) (defparameter *head-dim* 4)
(defparameter *state-dict* (make-hash-table :test 'equal)) (defparameter *params* nil)

;;; Autograd
(declaim (ftype (function (t t t) t) print-value))

(defstruct (value (:print-function print-value) (:constructor %make-value))
  (data 0.0 :type single-float) (grad 0.0 :type single-float)
  (children nil) (local-grads nil))

(defun print-value (v s d) (declare (ignore d))
  (format s "<Value ~A/~A>" (value-data v) (value-grad v)))

(defun ensure (v) (if (value-p v) v (%make-value :data (float v 1.0))))
(defun make-value (d &optional ch lg)
  (%make-value :data (if (value-p d) (value-data d) (float d 1.0)) :children ch :local-grads lg))

(defun v+ (a b)
  (let ((a (ensure a)) (b (ensure b)))
    (make-value (+ (value-data a) (value-data b)) (list a b) '(1.0 1.0))))
(defun v* (a b)
  (let ((a (ensure a)) (b (ensure b)))
    (make-value (* (value-data a) (value-data b)) (list a b) (list (value-data b) (value-data a)))))
(defun vpow (v p)
  (let ((v (ensure v)))
    (make-value (expt (value-data v) p) (list v)
                (list (coerce (* p (expt (value-data v) (1- p))) 'single-float)))))
(defun vlog (v) (let ((v (ensure v))) (make-value (log  (value-data v)) (list v) (list (/ 1.0 (value-data v))))))
(defun vexp (v) (let ((v (ensure v))) (make-value (exp  (value-data v)) (list v) (list (exp (value-data v))))))
(defun vrelu (v) (let ((v (ensure v))) (make-value (max 0.0 (value-data v)) (list v) (list (if (plusp (value-data v)) 1.0 0.0)))))
(defun vneg (v) (v* v -1.0))
(defun v- (a b) (v+ a (vneg b)))
(defun v/ (a b) (v* a (vpow b -1.0)))

(defun backward (v)
  (let ((topo nil) (seen (make-hash-table :test 'eq)))
    (labels ((build (n)
               (unless (gethash n seen)
                 (setf (gethash n seen) t)
                 (mapc #'build (value-children n))
                 (push n topo))))
      (build v))
    (setf (value-grad v) 1.0)
    (dolist (n topo)
      (mapc (lambda (c g) (incf (value-grad c) (* g (value-grad n))))
            (value-children n) (value-local-grads n)))))

;;; Model Parameters
(defun make-matrix (nout nin &optional (std 0.08))
  (coerce (loop for i below nout collect
                (coerce (loop for j below nin collect
                              (let ((v (make-value (random-gauss 0 std))))
                                (push v *params*) v))
                        'vector))
          'vector))

(defun init-model ()
  (setf *state-dict* (make-hash-table :test 'equal) *params* nil)
  (flet ((mat (k r c) (setf (gethash k *state-dict*) (make-matrix r c))))
    (mat "wte" *vocab-size* *n-embd*) (mat "wpe" *block-size* *n-embd*) (mat "lm_head" *vocab-size* *n-embd*)
    (dotimes (i *n-layer*)
      (flet ((lmat (s r c) (mat (format nil "layer~A.~A" i s) r c)))
        (lmat "attn_wq" *n-embd* *n-embd*) (lmat "attn_wk" *n-embd* *n-embd*)
        (lmat "attn_wv" *n-embd* *n-embd*) (lmat "attn_wo" *n-embd* *n-embd*)
        (lmat "mlp_fc1" (* 4 *n-embd*) *n-embd*) (lmat "mlp_fc2" *n-embd* (* 4 *n-embd*)))))
  (setf *params* (nreverse *params*)))

;;; Architecture
(defun vsum (vs) (reduce #'v+ vs :initial-value (make-value 0.0)))
(defun vlinear (x w)
  (loop for row across w
        collect (reduce #'v+ (mapcar #'v* (coerce row 'list) x) :initial-value (make-value 0.0))))
(defun vsoftmax (logits)
  (let* ((mx (reduce #'max logits :key #'value-data))
         (exps (mapcar (lambda (v) (vexp (v- v mx))) logits))
         (sum (vsum exps)))
    (mapcar (lambda (e) (v/ e sum)) exps)))
(defun vrmsnorm (x)
  (let ((sc (vpow (v+ (v/ (vsum (mapcar (lambda (xi) (v* xi xi)) x)) (length x)) 1e-5) -0.5)))
    (mapcar (lambda (xi) (v* xi sc)) x)))
(defun make-kv-cache ()
  (coerce (loop for i below *n-layer* collect (make-array 0 :fill-pointer 0 :adjustable t)) 'vector))

(defun gpt (tok-id pos-id keys vals)
  (let ((x (mapcar #'v+ (coerce (aref (gethash "wte" *state-dict*) tok-id) 'list)
                        (coerce (aref (gethash "wpe" *state-dict*) pos-id) 'list))))
    (setf x (vrmsnorm x))
    (dotimes (li *n-layer*)
      (flet ((sd (s) (gethash (format nil "layer~A.~A" li s) *state-dict*)))
        (let ((xr x))
          (setf x (vrmsnorm x))
          (let* ((q (vlinear x (sd "attn_wq")))
                 (k (vlinear x (sd "attn_wk")))
                 (v (vlinear x (sd "attn_wv"))))
            (vector-push-extend k (aref keys li))
            (vector-push-extend v (aref vals li))
            (setf x (vlinear
                     (loop for h below *n-head* nconc
                           (let* ((hs (* h *head-dim*)) (he (+ hs *head-dim*))
                                  (q-h (subseq q hs he))
                                  (k-h (map 'list (lambda (ki) (subseq ki hs he)) (aref keys li)))
                                  (v-h (map 'list (lambda (vi) (subseq vi hs he)) (aref vals li)))
                                  (aw (vsoftmax (loop for kt in k-h collect
                                                      (v/ (vsum (mapcar #'v* q-h kt)) (sqrt *head-dim*))))))
                             (loop for j below *head-dim* collect
                                   (vsum (mapcar (lambda (w vt) (v* w (nth j vt))) aw v-h)))))
                     (sd "attn_wo")))
            (setf x (mapcar #'v+ x xr))))
        (let ((xr x))
          (setf x (vrmsnorm x))
          (setf x (mapcar #'vrelu (vlinear x (sd "mlp_fc1"))))
          (setf x (vlinear x (sd "mlp_fc2")))
          (setf x (mapcar #'v+ x xr)))))
    (vlinear x (gethash "lm_head" *state-dict*))))

;;; Training
(defun run-training ()
  (let* ((lr 0.01) (b1 0.85) (b2 0.99) (eps 1e-8) (steps 1000) (np (length *params*))
         (m (make-array np :initial-element 0.0)) (mv (make-array np :initial-element 0.0)))
    (dotimes (step steps)
      (let* ((doc (nth (mod step (length *docs*)) *docs*))
             (tokens (append (list *bos*)
                             (loop for ch across doc collect (position ch *uchars*))
                             (list *bos*)))
             (n (min *block-size* (1- (length tokens))))
             (keys (make-kv-cache)) (vals (make-kv-cache)) (losses nil))
        (dotimes (pos n)
          (let* ((logits (gpt (nth pos tokens) pos keys vals))
                 (probs (coerce (vsoftmax logits) 'vector)))
            (push (vneg (vlog (aref probs (nth (1+ pos) tokens)))) losses)))
        (let* ((loss (v/ (vsum losses) n)) (t+1 (1+ step)))
          (backward loss)
          (loop for i below np for p in *params* do
                (setf (aref m i) (+ (* b1 (aref m i)) (* (- 1 b1) (value-grad p))))
                (setf (aref mv i) (+ (* b2 (aref mv i)) (* (- 1 b2) (expt (value-grad p) 2))))
                (let ((mh (/ (aref m i) (- 1 (expt b1 t+1))))
                      (vh (/ (aref mv i) (- 1 (expt b2 t+1)))))
                  (decf (value-data p) (/ (* lr (- 1 (/ step steps)) mh) (+ (sqrt vh) eps)))
                  (setf (value-grad p) 0.0)))
          (format t "step ~4D/~4D | loss ~,4F~%" t+1 steps (value-data loss))
          (finish-output))))))

;;; Inference
(defun random-choice (weights)
  (let ((r (random (reduce #'+ weights))) (acc 0.0))
    (dotimes (i (1- (length weights)) (1- (length weights)))
      (incf acc (aref weights i))
      (when (< r acc) (return-from random-choice i)))))

(defun run-inference ()
  (format t "~%--- inference (new, hallucinated names) ---~%")
  (dotimes (i 20)
    (let ((keys (make-kv-cache)) (vals (make-kv-cache)) (tok *bos*) (sample nil))
      (dotimes (pos *block-size*)
        (let* ((lt (mapcar (lambda (l) (/ (value-data l) 0.5)) (gpt tok pos keys vals)))
               (mx (reduce #'max lt))
               (exps (mapcar (lambda (v) (exp (- v mx))) lt))
               (probs (coerce (mapcar (lambda (e) (/ e (reduce #'+ exps))) exps) 'vector)))
          (setf tok (random-choice probs))
          (if (= tok *bos*) (return) (push (char *uchars* tok) sample))))
      (format t "sample ~2D: ~A~%" (1+ i) (coerce (reverse sample) 'string)))))

;;; Main
(defun run-microgpt ()
  (setf *random-state* (make-random-state t)
        *docs* (shuffle-list (read-lines "names.txt")))
  (format t "num docs: ~A~%" (length *docs*))
  (let ((chars nil))
    (dolist (doc *docs*) (loop for ch across doc do (pushnew ch chars)))
    (setf *uchars* (coerce (sort chars #'char<) 'string)
          *bos* (length *uchars*)
          *vocab-size* (1+ *bos*)))
  (format t "vocab size: ~A~%" *vocab-size*)
  (init-model)
  (format t "num params: ~A~%" (length *params*))
  (run-training)
  (run-inference))

(microgpt:run-microgpt)
